const config = {
		product: [
			{name: 'features', link: 'https://sentry.io/features/'},
			{name: 'pricing', link: 'https://sentry.io/pricing/'},
			{name: 'documentation', link: 'https://docs.sentry.io/'},
			{name: 'integrations', link: 'https://sentry.io/integrations/'},
			{name: 'status', link: 'https://status.sentry.io/'},
		],
		company: [
      {name: 'blog', link: 'https://blog.sentry.io/'},
			{name: 'about us', link: 'https://sentry.io/about/'},
      {name: 'careers', link: 'https://sentry.io/careers/'},
      {name: 'customers', link: 'https://sentry.io/customers/'},
			{name: 'community', link: 'https://sentry.io/community/'},
			{name: 'open source', link: 'https://open.sentry.io/'},
			{name: 'in the news', link: 'https://sentry.io/about/#press'},
			{name: 'media resources', link: 'https://sentry.io/about/media-resources/'},
			{name: 'engineering blog', link: 'https://sentry.engineering/'},
		],
		information: [
			{name: 'trust center', link: 'https://sentry.io/trust/'},
			{name: 'security & compliance', link: 'https://sentry.io/security/'},
			{name: 'privacy', link: 'https://sentry.io/privacy/'},
			{name: 'california privacy notice', link: 'https://sentry.io/trust/privacy/california/'},
			{name: 'terms', link: 'https://sentry.io/terms/'},
			{name: 'transparency report', link: 'https://sentry.io/legal/transparency-report/'},
			{name: 'support', link: 'https://help.sentry.io/'},
			{name: 'resources', link: 'https://sentry.io/resources/'},
			{name: 'answers', link: 'https://sentry.io/answers/'},
		],
		platforms: [
			{name: 'javascript', link: '/for/javascript'},
			{name: '.net', link: '/for/dot-net/'},
			{name: 'python', link: '/for/python/'},
			{name: 'android', link: '/for/android/'},
			{name: 'php', link: '/for/php/'},
			{name: 'django', link: '/for/django/'},
			{name: 'java', link: '/for/java/'},
			{name: 'flask', link: '/for/flask/'},
			{name: 'ruby', link: '/for/ruby/'},
			{name: 'laravel', link: '/for/laravel/'},
			{name: 'ios', link: '/for/ios/'},
			{name: 'rails', link: '/for/rails/'},
			{name: 'node', link: '/for/node/'},
			{name: 'react', link: '/for/react/'},
			{name: 'go', link: '/for/go/'},
		],
}

export default config;
